name: 3dgan_inversion_deca
channels:
  - pytorch
  - nvidia
  - iopath
  - conda-forge
  - soumith
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0=mkl
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - colorama=0.4.4
  - cudatoolkit=10.2.89
  - freetype=2.11.0
  - fvcore=0.1.5.post20210804
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - iopath
  - jpeg
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - numpy=1.21.1
  - olefile=0.46
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.2.4
  - portalocker=2.3.2
  - python=3.9.7
  - python_abi=3.9
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - pyyaml=5.4.1
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tabulate=0.8.9
  - termcolor=1.1.0
  - tk=8.6.11
  - torchvision=0.2.2
  - tqdm=4.62.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - chumpy==0.70
    - face-alignment==1.3.5
    - imageio==2.19.0
    - kornia==0.6.4
    - llvmlite==0.38.0
    - networkx==2.8
    - numba==0.55.1
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pyparsing==3.0.8
    - pywavelets==1.3.0
    - scikit-image==0.19.2
    - scipy==1.8.0
    - tifffile==2022.4.28
    - trimesh==3.12.0
